guru-br/catalogo_empresas

README.md
Adicionado empresas Creditas, GetNinjas e Plataformatec
=> Adicionando empresas de São Paulo

README.md
Adicionando M4U, Indeva e SkyHub para o RJ, e Dito para MG.
=> Adiciona empresas do RJ e MG

README.md
The title is self explanatory. ;)
=> Adds Guava to the companies list

README.md
Apenas uma sugestão de fix pra identações que estavam fora do padrão, e faltando algumas quebras de linha.
=> fixing identation and typos

README.md
Empresa que usa ruby on rails no estado do ceará
=> adding a ruby company based in Ceará

README.md
Adicionando a Resultados Digitais no Sul e Sudeste. 
Um problema: no Sul temos o office em Florianópolis (matriz) e em Joinville (coworking). É preciso especificar isso na lista? Por exemplo adicionar **- matriz & coworking** ao lado do nome.
=> Nova empresa!

README.md
Adicionei a RD em SC e SP identificando a matriz (SC)
=> Adds RD (sul e sudeste)

CONTRIBUTING.md
Adicionado no CONTRIBUTING.md como e onde adicionar empresas que não tem escritório físico
=> Empresas sem escritório físico

README.md
Adicionando a empresa Codeminer 42 no estado de Goiás.
=> Adding codeminer 42 into Goiás

README.md
As soon as Husky does not have a physical office (proudly) I've created a new menu called `Remoto`. If it's not the appropriate place to include the company link, let me know.
=> Include `remote` location and new company

README.md
Rebase é uma empresa focada em desenvolvimento Web e especialista em Ruby on Rails. A empresa foi fundada pelos mesmos criadores da Campus Code.
=> Add Rebase

README.md
Gostaria de contribuir com a lista. 
Podem conferir nesse [link](http://algorich.com.br/trabalhe-conosco.html) que eles usam Rails no stack deles. 
Obrigado pela atenção.
=> Adiciona a Empresa Algorich de Campos dos Goytacazes (RJ)

README.md
Finally merging lists \o/ :green_heart: 
Directly from [RubyFloripa/jobs](https://github.com/RubyFloripa/jobs)
=> Add companies list found in RubyFloripa/jobs repo

README.md
[As commented](https://github.com/guru-br/catalogo_empresas/pull/67#discussion_r263205926) by @odineiramone, previous URL for GoGood company wasn't working.
=> Update GoGood URL

README.md
Adicionei + 4 empresas que trabalham com Rails a medida que encontra outras empresas irei adicionando. 👍
=> adicionando novas empresas

README.md
[Ebert is now SourceLevel!](https://sourcelevel.io/ebert-is-now-sourcelevel) :tada:
=> Rename Ebert to SourceLevel

README.md
Signed-off-by: Anderson Fernandes <fernandesanderson14@gmail.com>
=> Add Stant to Alagoas

README.md
Fusion between Edools and Eadbox resulting in Hero Spark
=> removing Edools, adding Hero Spark

README.md
Adiciona Globo.com em São Paulo também. 
Adiciona Prevision, que eu encontrei em um site de vagas e trabalha com Ruby.
=> Add Prevision

README.md
Uma organização com sólida experiência no setor financeiro, que cria soluções inovadoras e customizadas para seus clientes, focada em agregar ainda mais valor para o seu negócio. Assim pode ser descrita a Cashway, uma empresa que transformou seu vasto conhecimento de mercado em soluções especializadas para atender as atuais necessidades de cooperativas rurais, sindicatos, cooperativas de crédito, financeiras, agroindústrias e associações em geral.
Nossos sistemas são desenvolvidos em Rails, React e Flutter.
=> Adiciona a CashWay de Florianópolis/SC ❤️

README.md
A stack principal da empresa é RoR
=> Add Certus at Curitiba

README.md
Added Ruptiva a company from Santa Catarina.
=> Add Ruptiva

README.md
Uma Startup de desenvolvimento soluções de software, com foco em ajudar os clientes a inovar, se diferenciar e crescer. Construindo aplicações web inseridas em contextos de alta complexidade e necessidade específicas para cada negócio.
=> Adiciona A Brasil System de Fortaleza-CE

README.md
Adding Inovamind Tech LTDA in the company list.
=> feat: Adding new company

README.md
More details at:
https://www.agendor.com.br
https://jobs.kenoby.com/agendor
https://www.linkedin.com/company/agendor/
=> Contributing with Agendor to Full Remote Companies

README.md
> A Blu é uma empresa com presença digital em todo o Brasil com a missão de conectar o varejo e a indústria por meio de soluções financeiras.
See more: https://blu.com.br
Job postings: https://vemprablu.gupy.io
=> Add Blu to companies list from Rio de Janeiro (RJ)

README.md
Olá pessoal, 
Parabéns pela iniciativa. Estou adicionando a empresa Pipefy para a lista, onde estamos frequentemente contratando pessoas desenvolvedoras Ruby on Rails.
=> adding Pipefy to the list

README.md
=> Adding Knowbe4 company

README.md
algumas empresas que fiz entrevista e trabalham com Ruby.
=> novas empresas

README.md
Olá pessoal :wave:
A `In Loco` pivotou seu produto e agora chama-se `Incognia`.
=> Updates In Loco to Incognia and sets as remote work

README.md
Falei com um gerente de ti deles hoje. O único produto que eles tinham com ruby foi descontinuado e o time desmontado. Hoje ele estão utilizando C#
=> Removendo o grupo Fortes

README.md
=> Adicionando a gocase

README.md
O Easy Pallet é a primeira solução digital conhecida no Brasil que abrange toda a operação de picking de ponta a ponta, desde a montagem e conferência de paletes até a liberação dos veículos e a sua completa gestão por meio de indicadores em tempo real e diversos relatórios via painéis, tabelas e gráficos.
Todo o nosso time trabalha remotamente e estamos distribuídos pelos Brasil.
Nossa stack principal é feita em Ruby on Rails.
=> Adiciona a empresa Easy Pallet.

README.md
=> Adicionando empresa Nave.Bild

README.md
=> Add TotalPass

README.md
Adicionando a empresa Claretiano Rede de Educação
=> Adiciona Claretiano

README.md
=> Add RenoFi

README.md
Adiciona a empresa Switch Dreams do DF.
=> Adiciona Switch Dreams - DF

README.md
Opa, estou adicionando algumas empresas aqui do Ceará que usam Ruby.
=> add: ceara_companies

README.md
Adiciona [Reserva INK](https://reserva.ink) e remove a Reserva, pois eles utilizam a JS/TS e seus frameworks.
=> Adiciona Reserva INK e remove Reserva

README.md
Este PR adiciona a empresa [Parafuzo](https://parafuzo.com/), de intermediação de serviços, na qual trabalho e se localiza em SP, capital.
=> Adiciona empresa Parafuzo

README.md
Add Blue AI na lista de empresas Sem escritório físico
=> Add Blue AI

README.md
Planisa has a product legacy in Java and all others products in Rails and Rails + React
=> add Planisa company

CONTRIBUTING.md
Change from `Empressas` to `Empresas`
=> Correct tpo

README.md
add 'Kompra.app' company to the list
=> add 'Kompra.app' company to the list

README.md
Hello, sou Wallisson Adicione á empresa JungleDevs - SC.
=> Adicionar empresa JungleDevs
